# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setGeometry(QtCore.QRect(140, 160, 113, 32))
        self.button_submit.setObjectName("button_submit")
        self.label_help = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_help.setGeometry(QtCore.QRect(29, 220, 341, 20))
        self.label_help.setText("")
        self.label_help.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_help.setObjectName("label_help")
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(120, 10, 175, 21))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_id = QtWidgets.QLabel(parent=self.splitter)
        self.label_id.setObjectName("label_id")
        self.input_id = QtWidgets.QLineEdit(parent=self.splitter)
        self.input_id.setObjectName("input_id")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 80, 72, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_jane = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton_jane.setObjectName("radioButton_jane")
        self.radio_group = QtWidgets.QButtonGroup(MainWindow)
        self.radio_group.setObjectName("radio_group")
        self.radio_group.addButton(self.radioButton_jane)
        self.verticalLayout.addWidget(self.radioButton_jane)
        self.radioButton_john = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton_john.setObjectName("radioButton_john")
        self.radio_group.addButton(self.radioButton_john)
        self.verticalLayout.addWidget(self.radioButton_john)
        self.label_heading = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_heading.setGeometry(QtCore.QRect(160, 60, 69, 25))
        self.label_heading.setObjectName("label_heading")
        self.button_results = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_results.setGeometry(QtCore.QRect(140, 290, 113, 32))
        self.button_results.setObjectName("button_results")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_submit.setText(_translate("MainWindow", "SUBMIT"))
        self.label_id.setText(_translate("MainWindow", "Voter ID"))
        self.radioButton_jane.setText(_translate("MainWindow", "Jane"))
        self.radioButton_john.setText(_translate("MainWindow", "John"))
        self.label_heading.setText(_translate("MainWindow", "Candidates"))
        self.button_results.setText(_translate("MainWindow", "View Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
